// Generated by gencpp from file autoku_msgs/VehicleOutput.msg
// DO NOT EDIT!


#ifndef AUTOKU_MSGS_MESSAGE_VEHICLEOUTPUT_H
#define AUTOKU_MSGS_MESSAGE_VEHICLEOUTPUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace autoku_msgs
{
template <class ContainerAllocator>
struct VehicleOutput_
{
  typedef VehicleOutput_<ContainerAllocator> Type;

  VehicleOutput_()
    : id()
    , x(0.0)
    , y(0.0)
    , yaw(0.0)
    , velocity(0.0)  {
    }
  VehicleOutput_(const ContainerAllocator& _alloc)
    : id(_alloc)
    , x(0.0)
    , y(0.0)
    , yaw(0.0)
    , velocity(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _id_type;
  _id_type id;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef double _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::autoku_msgs::VehicleOutput_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autoku_msgs::VehicleOutput_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleOutput_

typedef ::autoku_msgs::VehicleOutput_<std::allocator<void> > VehicleOutput;

typedef boost::shared_ptr< ::autoku_msgs::VehicleOutput > VehicleOutputPtr;
typedef boost::shared_ptr< ::autoku_msgs::VehicleOutput const> VehicleOutputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autoku_msgs::VehicleOutput_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autoku_msgs::VehicleOutput_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autoku_msgs::VehicleOutput_<ContainerAllocator1> & lhs, const ::autoku_msgs::VehicleOutput_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.yaw == rhs.yaw &&
    lhs.velocity == rhs.velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autoku_msgs::VehicleOutput_<ContainerAllocator1> & lhs, const ::autoku_msgs::VehicleOutput_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autoku_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::autoku_msgs::VehicleOutput_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autoku_msgs::VehicleOutput_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoku_msgs::VehicleOutput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoku_msgs::VehicleOutput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoku_msgs::VehicleOutput_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoku_msgs::VehicleOutput_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autoku_msgs::VehicleOutput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8e71ca8b40f5ece91a4b535460967ce7";
  }

  static const char* value(const ::autoku_msgs::VehicleOutput_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8e71ca8b40f5ece9ULL;
  static const uint64_t static_value2 = 0x1a4b535460967ce7ULL;
};

template<class ContainerAllocator>
struct DataType< ::autoku_msgs::VehicleOutput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autoku_msgs/VehicleOutput";
  }

  static const char* value(const ::autoku_msgs::VehicleOutput_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autoku_msgs::VehicleOutput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string id \n"
"float64 x\n"
"float64 y\n"
"float64 yaw\n"
"float64 velocity\n"
;
  }

  static const char* value(const ::autoku_msgs::VehicleOutput_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autoku_msgs::VehicleOutput_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.yaw);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleOutput_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autoku_msgs::VehicleOutput_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autoku_msgs::VehicleOutput_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.id);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOKU_MSGS_MESSAGE_VEHICLEOUTPUT_H
